export const reset = "\x1b[0m";   // Reset to default color
export const black = "\x1b[30m";  // Black
export const red = "\x1b[31m";    // Red
export const green = "\x1b[32m";  // Green
export const yellow = "\x1b[33m"; // Yellow
export const blue = "\x1b[34m";   // Blue
export const magenta = "\x1b[35m";// Magenta (Purple)
export const cyan = "\x1b[36m";   // Cyan
export const white = "\x1b[37m";  // White